### ISSUE TITLE
No particles in 3D example

### ISSUE THREAD

**Issue by PrometheusPi** [RemiLehe/openPMD-example-datasets#4]
There are no particles in the 3D example data set.

**Comment by ax3l** [comment]
@RemiLehe do you have some?

**Comment by RemiLehe** [comment]
The particles were not added for the sake of manageable file size. (In order to run the openPMD-viewer tutorial, the user needs to download the example-datasets, which already takes a little bit of time without the 3D particles.) Moreover, in principle, the particles are not read different whether the file is 2D or 3D. 

If you do need the 3D particles for some applications (3D plotting for instance), one possibility would be to include a subset of the particles in the file. But then we would have to choose exactly which type of particles to select (selection in energy ? in position ?)

What do you think ?

**Comment by ax3l** [comment]
I though a very rough number of particles per cell (say 2) will result in a increase in the file size not larger than adding an other vector field.

So basically: just using a simulation with a badly resolved particle space.

**Comment by RemiLehe** [comment]
Well, a particle has at least 6 quantities (positions and momenta), so adding 2 particles per cell is like adding 12 quantities, which is the same size as 4 vector fields. The current data has 3 vector fields plus 1 scalar field, so it will more than double the size, am I correct ?

But I agree this is still manageable. I'll try to do a pull request soon.

**Comment by ax3l** [comment]
ah yes it was a long day yesterday and I was only thinking positions.
